services:
  api:
    image: vagner8/up.api:latest
    ports:
      - "8080:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT}
      Jwt__Key: ${JWT_KEY}
      ConnectionStrings__DefaultConnection: "Host=postgres;Port=5432;Database=UpDb;Username=postgres;Password=${POSTGRES_PASSWORD}"
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:17
    environment:
      POSTGRES_DB: UpDb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d UpDb"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: