env:
  TERRAFORM_DIR: UP.Infrastructure/Terraform/Environments/Dev
  UP_API_IMAGE_ADDRESS: ${{ secrets.DOCKERHUB_USERNAME }}/up.api:${{github.sha}}

name: CI

on:
  push:
    branches:
      - master
      - develop

  pull_request:
    branches:
      - master
      - develop

permissions:
  id-token: write
  contents: read

jobs:
  # Integration-tests:
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v4

  #     - name: Setup .NET
  #       uses: actions/setup-dotnet@v4
  #       with:
  #         dotnet-version: '10.0.x'

  #     - name: Restore UP.Api
  #       run: dotnet restore UP.Api/UP.Api.csproj

  #     - name: Check API formatting
  #       run: dotnet format UP.Api/UP.Api.csproj --verify-no-changes --no-restore --exclude UP.Api/Migrations

  #     - name: Check integration tests formatting
  #       run: dotnet format UP.IntegrationTests/UP.IntegrationTests.csproj --verify-no-changes --no-restore

  #     - name: Run tests
  #       run: dotnet test UP.IntegrationTests/UP.IntegrationTests.csproj
  
  Build:
    runs-on: ubuntu-latest
    environment: Dev
    # needs: Integration-tests

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build \
            -f UP.Api/Dockerfile \
            -t "$UP_API_IMAGE_ADDRESS" \
            .

      - name: Push Docker image
        run: |
          docker push "$UP_API_IMAGE_ADDRESS"

  Deploy:
    runs-on: ubuntu-latest
    environment: Dev
    needs: Build

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Debug OIDC claims
        uses: actions/github-script@v7
        with:
          script: |
            const token = await core.getIDToken('sts.amazonaws.com');
            const payload = JSON.parse(
              Buffer.from(token.split('.')[1], 'base64url').toString()
            );

            console.log('OIDC claims:');
            console.log('iss:', payload.iss);
            console.log('aud:', payload.aud);
            console.log('sub:', payload.sub);

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
            role-to-assume: arn:aws:iam::558613451057:role/up-api-dev-github-role
            role-session-name: github-actions-${{ github.run_id }}
            aws-region: eu-central-1
            retry-max-attempts: 1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        working-directory: ${{ env.TERRAFORM_DIR }}
        run: terraform init

      - name: Debug Terraform files
        working-directory: ${{ env.TERRAFORM_DIR }}
        run: |
          pwd
          echo "Files:"
          ls -la

          echo "terraform.tfvars:"
          cat terraform.tfvars

      - name: Terraform Plan
        working-directory: ${{ env.TERRAFORM_DIR }}
        run: |
          terraform plan \
            -var="up_api_image_address=$UP_API_IMAGE_ADDRESS"

      - name: Terraform Apply
        working-directory: ${{ env.TERRAFORM_DIR }}
        run: |
          terraform apply \
            -auto-approve \
            -var="up_api_image_address=$UP_API_IMAGE_ADDRESS"

      - name: Get API URL
        working-directory: ${{ env.TERRAFORM_DIR }}
        run: |
          echo "API_URL=http://$(terraform output -raw public_ip):8080/health" >> "$GITHUB_ENV"

      - name: Wait for API
        run: |
          echo "Waiting for API at $API_URL..."

          for i in {1..30}; do
            if curl --fail --silent --show-error "$API_URL"; then
              echo ""
              echo "API is ready!"
              exit 0
            fi

            echo "API is not ready yet. Attempt $i/30..."
            sleep 10
          done

          echo "API did not become ready after 5 minutes."
          exit 1