name: CI

on:
  push:
    branches:
      - master
      - develop

  pull_request:
    branches:
      - master
      - develop

jobs:
  Integration-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'

      - name: Restore UP.Api
        run: dotnet restore UP.Api/UP.Api.csproj

      - name: Check API formatting
        run: dotnet format UP.Api/UP.Api.csproj --verify-no-changes --no-restore --exclude UP.Api/Migrations

      - name: Check integration tests formatting
        run: dotnet format UP.IntegrationTests/UP.IntegrationTests.csproj --verify-no-changes --no-restore

      - name: Run tests
        run: dotnet test UP.IntegrationTests/UP.IntegrationTests.csproj